name : Create Release

on:
  workflow_run:
    workflows: ["Production CI/CD"]
    types:
      - completed

jobs: 
  create_release_job:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    name: Create Release Job
    steps:
      - name: Get Release Number
        id: package.json-version
        uses: martinbeentjes/npm-get-version-action@master
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ steps.package.json-version.outputs.current-version}}
          release_name: Release ${{ steps.package.json-version.outputs.current-version}}
