name: Create Pull Request

on:
  repository_dispatch:
    types: [my-event]

jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: pull-request
      uses: repo-sync/pull-request@v2
      with:
        source_branch: "develop"
        destination_branch: "main"
        github_token: ${{ secrets.GITHUB_TOKEN }}        