name: Merge Pull Request


on:
  pull_request_target:
    types: [opened]
    branches:
      - main

jobs:
  auto-approve:
    runs-on: ubuntu-latest
    steps:
    - uses: hmarr/auto-approve-action@v2
      if: github.actor == 'github-actions[bot]'
      with:
        github-token: "${{ secrets.GITHUB_TOKEN }}"