name: Merge Pull Request

on:
  workflow_run:
    types:
      - completed
    workflows:
      - 'Create Pull Request'

jobs:
  merge-request:
    runs-on: ubuntu-latest
    steps:
      - if: ${{ github.event.workflow_run.conclusion == 'success' }}
      - name: merge-request
        uses: ridedott/merge-me-action@v2
        with:
          GITHUB_LOGIN: github-actions
          GITHUB_TOKEN: ${{ secrets.ACTIONS_BOTPAT }}
          MERGE_METHOD: MERGE