name: Merge Pull Request

on:
  workflow_run:
    types:
      - completed
    workflows:
      - 'Create Pull Request'

jobs:
  merge-request:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Approve Pull Request
        uses: juliangruber/approve-pull-request-action@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          number: 1